server:
  port: 8084

spring:
  cloud:
    gateway:
      routes:
      - id: company1
        uri: http://localhost:8081/
        predicates:
        - Path=/companies/**
      - id: company2
        uri: http://localhost:8082/
        predicates:
        - Path=/companies/**
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka